name: Eleventy Build Staging Pantheon WP 5.8.1
# site: https://staging.drought.ca.gov
# editor: https://live-drought-ca-gov.pantheonsite.io
# s3 bucket: http://staging.drought.ca.gov.s3-website-us-west-1.amazonaws.com/
on:
on:
  push:
    branches:
      - staging
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@master
      - name: Use Node.js 14.17.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      - name: Build 11ty
        run: |
          mkdir dist
          npm install
          npm run build

      # # Push built site files to S3 production bucket    
      # - name: Deploy to S3
      #   uses: jakejarvis/s3-sync-action@v0.5.1
      #   with:
      #     args: --acl public-read --follow-symlinks --delete
      #   env:
      #     AWS_S3_BUCKET: 'drought.ca.gov'
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
      #     SOURCE_DIR: ./docs # only move built directory

      # # Invalidate Cloudfront production distribution
      # - name: invalidate
      #   uses: chetan/invalidate-cloudfront-action@v1.3
      #   env:
      #     DISTRIBUTION: 'E2L7RQ19YAOM45'
      #     PATHS: '/*'
      #     AWS_REGION: 'us-west-1'
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    

      # deploy built files to separate branch that contains only built files that github pages uses to serve site
      - name: Deploy to github pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: deploy_production
        env:
          SITE_DOMAIN: "https://staging.drought.ca.gov"
          
      # Push just built site files to staging S3 bucket
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'staging.drought.ca.gov'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
          SOURCE_DIR: ./docs # only move built directory

      # Invalidate staging Cloudfront distribution
      - name: invalidate
        uses: chetan/invalidate-cloudfront-action@v1.3
        env:
          DISTRIBUTION: 'E1FCC4093TP0Q2'
          PATHS: '/*'
          AWS_REGION: 'us-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}