name: Eleventy Build Main
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: 
      - "Fetch Drought Data"
    types: 
      - completed
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@master
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Build 11ty
        run: |
          mkdir dist
          npm ci --production
          npm run build
      - name: Write robots.txt
        run: |
          echo 'User-agent: *' > docs/robots.txt
          echo 'Allow: /' >> docs/robots.txt
          echo 'Sitemap: https://drought.ca.gov/sitemap.xml' >> docs/robots.txt
      # Push built site files to S3 production bucket    
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'drought.ca.gov'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
          SOURCE_DIR: ./docs # only move built directory
      # Reset the cache-control headers on static assets on production S3 bucket
      - name: Reset cache-control on fonts
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: 'us-west-1'   # optional: defaults to us-east-1
          source: './docs/fonts'
          dest: 's3://drought.ca.gov/fonts'
          flags: --recursive --cache-control max-age=15552000
      - name: Reset cache-control on assets
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: 'us-west-1'   # optional: defaults to us-east-1
          source: './docs/assets'
          dest: 's3://drought.ca.gov/assets'
          flags: --recursive --cache-control max-age=15552000
      - name: Reset cache-control on media
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: 'us-west-1'   # optional: defaults to us-east-1
          source: './docs/media'
          dest: 's3://drought.ca.gov/media'
          flags: --recursive --cache-control max-age=15552000
      # Invalidate Cloudfront production distribution
      - name: invalidate
        uses: chetan/invalidate-cloudfront-action@v1.3
        env:
          DISTRIBUTION: 'E2L7RQ19YAOM45'
          PATHS: '/*'
          AWS_REGION: 'us-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}