name: Eleventy Build Main
on:
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build 11ty
        run: |
          npm install
          npm run build

      # deploy built files to separate branch that contains only built files that github pages uses to serve site
      - name: Deploy to github pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: deploy_production
          


