name: Eleventy Build Master
on:
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build 11ty
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs
          publish_branch: deploy_production
          commit_message: ${{ github.event.head_commit.message }}
