name: Generate Drought Map

on:
  push:
    branches:
      - automate-drought-map
  schedule:
    - cron: 0 6 * * 4

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Fetch current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'

      - name: Install dependencies
        run: |
          pip install -r src/py/generate-drought-map/requirements.txt
          sudo apt-get update
          sudo apt-get install pngcrush

      - name: Run script
        run: python src/py/generate-drought-map/process_usmap.py
        
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Weekly drought map for ${{ steps.date.outputs.today }}
          branch: automate-drought-map

